name: Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 13.5.0
      - run: npm ci --silent
      - run: echo //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}} > ~/.npmrc
      - run: cat ~/.npmrc
      - run: npm run test
      - run: npm run size
      - run: npm run build
      - run: npm publish
